server:
  port: 8083

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

  # Mail configuration
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}