server:
  port: 8083

spring:
  application:
    name: notification-service

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

  # Mail configuration
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}