version: "3.8"

services:
  mongo-match:
    image: mongo
    container_name: mongo-match
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: salmane
      MONGO_INITDB_DATABASE: match-service
    volumes:
      - ./data/mongo-match:/data/db
    networks:
      - stadium-hub-network

  mongo-ticket:
    image: mongo
    container_name: mongo-ticket
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: salmane
      MONGO_INITDB_DATABASE: ticket-service
    volumes:
      - ./data/mongo-ticket:/data/db
    networks:
      - stadium-hub-network

  mongo-booking:
    image: mongo
    container_name: mongo-booking
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: salmane
      MONGO_INITDB_DATABASE: booking-service
    volumes:
      - ./data/mongo-booking:/data/db
    networks:
      - stadium-hub-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - stadium-hub-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - stadium-hub-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_NAME: local
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: kafka:29092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - stadium-hub-network

  stadiumhub-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - '8761:8761'
    depends_on:
      - keycloak
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - '9999:9999'
    depends_on:
      stadiumhub-discovery-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${GIT_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${GIT_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - '8888:8888'
    depends_on:
      stadiumhub-config-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      # Keycloak
      - ISSUER_URI=${ISSUER_URI}
      - TOKEN_URI=${TOKEN_URI}
      - CLIENT_ID=${GATEWAY_CLIENT_ID}
      - CLIENT_SECRET=${GATEWAY_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-ticket-service:
    build: ./ticket-service
    container_name: ticket-service
    ports:
      - '8081:8081'
    depends_on:
      mongo-ticket:
        condition: 'service_started'
      stadiumhub-config-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - MONGODB_URL=mongodb://root:salmane@mongo-ticket:27017/ticket-service?authSource=admin
      # Keycloak
      - ISSUER_URI=${ISSUER_URI}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-match-service:
    build: ./match-service
    container_name: match-service
    ports:
      - '8080:8080'
    depends_on:
      mongo-match:
        condition: 'service_started'
      stadiumhub-ticket-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - MONGODB_URL=mongodb://root:salmane@mongo-match:27017/match-service?authSource=admin
      # Keycloak
      - ISSUER_URI=${ISSUER_URI}
      - TOKEN_URI=${TOKEN_URI}
      - CLIENT_ID=${MATCH_CLIENT_ID}
      - CLIENT_SECRET=${MATCH_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - '8082:8082'
    depends_on:
      mongo-booking:
        condition: 'service_started'
      kafka:
        condition: 'service_started'
      stadiumhub-config-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - MONGODB_URL=mongodb://root:salmane@mongo-booking:27017/booking-service?authSource=admin
      - KAFKA_URL=kafka:29092
      # Keycloak
      - ISSUER_URI=${ISSUER_URI}
      - TOKEN_URI=${TOKEN_URI}
      - CLIENT_ID=${BOOKING_CLIENT_ID}
      - CLIENT_SECRET=${BOOKING_CLIENT_SECRET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  stadiumhub-notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - '8083:8083'
    depends_on:
      kafka:
        condition: 'service_started'
      stadiumhub-config-service:
        condition: 'service_healthy'
    environment:
      - DISCOVERY_SERVICE_URL=${DISCOVERY_SERVICE_URL}
      - CONFIG_SERVICE_URL=${CONFIG_SERVICE_URL}
      - KAFKA_URL=kafka:29092
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - stadium-hub-network

  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    volumes:
      - ./data/keycloak_postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: salmane
    ports:
      - "5432:5432"
    networks:
      - stadium-hub-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.5
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: salmane
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: salmane
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8181:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      retries: 3
    depends_on:
      - keycloak-postgres
    networks:
      - stadium-hub-network

networks:
  stadium-hub-network:
    name: stadium-hub-network