server:
  port: 8082

spring:
  application:
    name: booking-service

  config:
    import: optional:configserver:config-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
