server:
  port: 8080

spring:
  application:
    name: match-service

  config:
    import: optional:configserver:config-service

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service