spring:
  application:
    name: match-service
  data:
    mongodb:
      uri: mongodb://root:salmane@localhost:27017/match-service?authSource=admin

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

eureka:
  instance:
    prefer-ip-address: true