server:
  port: 8080

spring:
  application:
    name: match-service

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8181/realms/stadiumhub-security-realm}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}