spring:
  application:
    name: match-service

  data:
    mongodb:
      uri: mongodb://root:salmane@localhost:27017/match-service?authSource=admin

  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

ticket:
  url: "http://localhost:8081"