server:
  port: 8081

spring:
  application:
    name: ticket-service

  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}